name: Deployment Workflow
on:
  push:
    branches:  
      - master 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy changes to server via ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: "foxtail.consulting"
        username: andrew
        key: ${{ secrets.FOXTAIL_SECRET }}
        port: 22
        script: |
          cd foxtail
          git pull origin master
          mix deps.get --only prod 
          npm install --prefix ./assets
          MIX_ENV=prod mix compile --force
          npm run deploy --prefix ./assets
          mix phx.digest
          MIX_ENV=prod mix release --overwrite
          _build/prod/rel/foxtail/bin/foxtail stop
          _build/prod/rel/foxtail/bin/foxtail daemon
